PI/Proiect/Grochery/urls.py
from django.urls import path
from Grochery import views

app_name = 'Grochery'
main_page_name = 'main_page'

urlpatterns=[
    path('inregistrare/', views.register, name='register'),
    path('user_login/',views.user_login,name='user_login'),
    path('food_list/',views.food_list,name='food_list'),
    path('add_food/',views.add_food,name='add_food'),
    path('edit_food/<int:food_id>/',views.edit_food, name='edit_food'),
    path('delete_food/<int:food_id>/',views.delete_food,name='delete_food'),
    path('main_page/',views.main_page, name='main_page'),
    path('shopping_lists/', views.shopping_lists, name='shopping_lists'),
    path('reset_password/',views.reset_password,name='reset_password'),
    
]

PI/Proiect/Proiect/urls.py
from django.contrib import admin
from django.urls import path,include
from Grochery import views



urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('Grochery/',include('Grochery.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
    


]

PI/Proiect/Grochery/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser,Group,Permission
from django.utils import timezone

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class Food(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    is_favorite = models.BooleanField(default=False)
    users = models.ManyToManyField(User, related_name='foods')
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    
    def __str__(self):
        return self.name

class ShoppingList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    foods = models.ManyToManyField(Food)
    
    meal_choices = [
        ('breakfast', 'Breakfast'),
        ('lunch', 'Lunch'),
        ('snack', 'Snack'),
        ('dinner', 'Dinner'),
        ('other', 'Other'),
    ]
    meal = models.CharField(max_length=10, choices=meal_choices)

    def __str__(self):
        return f"{self.user.username} - {self.name}"


class FavoriteFood(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    food = models.ForeignKey(Food, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.user.username} - {self.food.name}"
    
class CustomUser(AbstractUser):
    reset_token = models.CharField(max_length=255, blank=True, null=True)
    
    # Adaugă related_name pentru a evita conflictele
    groups = models.ManyToManyField(Group, verbose_name='groups', blank=True, related_name='customuser_set')
    user_permissions = models.ManyToManyField(Permission, verbose_name='user permissions', blank=True, related_name='customuser_set')

PI/Proiect/Grochery/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Food,ShoppingList

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User 
        fields = ('username','email','password')

class FoodForm(forms.ModelForm):
    class Meta:
        model = Food
        fields = ['name','price','is_favorite']

class ShoppingListForm(forms.ModelForm):
    class Meta:
        model = ShoppingList
        fields = ['name', 'meal']

PI/Proiect/Grochery/views.py
from django.shortcuts import render
from Grochery.forms import UserForm 


from django.http import HttpResponseRedirect, HttpResponse

from django.urls import reverse,reverse_lazy

from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from django.contrib import messages

from .models import Food, ShoppingList,FavoriteFood
from .forms import FoodForm,ShoppingListForm

from django.shortcuts import redirect,get_object_or_404
from django.http import JsonResponse
from django.utils import timezone
from django.core.mail import send_mail

# Create your views here.

def index(request):
    return render(request,'Grochery/index.html')

@login_required
def special(request):
    return HttpResponse("You are loged in")

@login_required
def user_logout(request):

    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)

        if user_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user.password)
            user.last_login = timezone.now()  # Set last_login here
            user.save()
            registered = True
        else:
            print(user_form.errors)
    else: 
        user_form = UserForm()

    return render(request, 'Grochery/inregistrare.html', {'user_form': user_form, 'registered': registered})
         
    
def user_login(request):

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)
        print("User: ",user)
        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('main_page'))
            else:
                return HttpResponse("Account not active")
        else:
            print("Someone tried to log in and failed")
            print("Username: {} and password: {}".format(username, password))
            return HttpResponse("Invalid login details")
    else:
        return render(request, 'Grochery/log_in.html')
    


    
def add_food(request):
    if request.method == 'POST':
        form = FoodForm(request.POST)
        if form.is_valid():
            food = form.save(commit=False)
            food.user = request.user  # Set the user to the currently logged-in user
            food.is_favorite = form.cleaned_data['is_favorite']
            food.save()
            return redirect('Grochery:food_list')
        else:
            print(form.errors)
    else:
        form = FoodForm()
    return render(request, 'Grochery/add_food.html', {'form': form})



@login_required
def food_list(request):
    sort_option = request.GET.get('sort', 'name')

    if sort_option == 'name':
        foods = Food.objects.filter(user=request.user).order_by('name')
    elif sort_option == '-name':
        foods = Food.objects.filter(user=request.user).order_by('-name')
    elif sort_option == 'is_favorite':
        foods = Food.objects.filter(user=request.user).order_by('-is_favorite', 'name')
    else:
        foods = Food.objects.filter(user=request.user)

    return render(request, 'Grochery/food_list.html', {'foods': foods})

def edit_food(request, food_id):
    food = get_object_or_404(Food, id=food_id)

    if request.method == 'POST':
        form = FoodForm(request.POST, instance=food)
        if form.is_valid():
            food = form.save(commit=False)
            food.is_favorite = form.cleaned_data['is_favorite']
            food.save()
            return redirect('Grochery:food_list')

    form = FoodForm(instance=food)
    return render(request, 'Grochery/edit_food.html', {'form': form})

def delete_food(request, food_id):
    food = get_object_or_404(Food, pk=food_id)
    food.delete()
    return HttpResponseRedirect(reverse('Grochery:food_list'))

def main_page(request):
    return render(request, 'Grochery/main.html')

def shopping_lists(request):
    user_lists = ShoppingList.objects.filter(user=request.user)
    return render(request, 'Grochery/shopping_lists.html', {'user_lists': user_lists})

def add_shopping_list(request):
    if request.method == 'POST':
        form = ShoppingListForm(request.POST)
        if form.is_valid():
            shopping_list = form.save(commit=False)
            shopping_list.user = request.user
            shopping_list.save()
            return redirect('Grochery:shopping_lists')
    else:
        form = ShoppingListForm()
    return render(request, 'Grochery/add_shopping_list.html', {'form': form})


def reset_password(request):
    if request.method == 'POST':
        email = request.POST.get('email', '')

        # Verifică dacă există un utilizator cu această adresă de email
        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            messages.error(request, 'Nu există niciun cont asociat acestei adrese de email.')
            return redirect('Grochery:reset_password')

        # Generează un token unic și salvează-l în baza de date sau trimite-l în email
        # Exemplu: user.reset_token = generate_unique_token()
        # user.save()

        # Trimite email-ul cu link-ul de resetare
        subject = 'Resetare parolă'
        message = f'Folosiți acest link pentru a vă reseta parola: {request.build_absolute_uri("/reset_password/")}?token={user.reset_token}'
        from_email = 'andrea.ciorba04@e-uvt.ro'
        to_email = [email]

        send_mail(subject, message, from_email, to_email, fail_silently=False)

        messages.success(request, 'Un email cu instrucțiuni pentru resetarea parolei a fost trimis.')
        return redirect('index')  # Redirecționează la pagina principală sau unde dorești
    else:
        return render(request, 'Grochery/reset_password.html')

PI/Proiect/templates/Grochery/add_food.html
<div class="jumbotron">
    <h2>Adauga un nou aliment</h2>
    <form method="post" action="{% url 'Grochery:add_food' %}">
      {% csrf_token %}
  
      {{ form.as_p}}
  
      <button type="submit">Adauga aliment</button>
    </form>
    <br>
    <a href="{% url 'index' %}"><button>Înapoi la Index</button></a>
</div>

PI/Proiect/templates/Grochery/add_shopping_list.html
{% extends "Grochery/base.html" %}
{% block body_block %}

<div class="container">
    <h1>Adaugă listă de cumpărături</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="" value="Salvează listă">
    </form>
    <a class="btn btn-secondary" href="{% url 'Grochery:shopping_lists' %}">Înapoi la listele de cumpărături</a>
</div>

{% endblock %}

PI/Proiect/templates/Grochery/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Pagina de Intrare{% endblock %}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            padding: 50px;
            background-color: #f8f9fa;
            color: #495057;
            margin: 0;
        }

        .navbar {
            overflow: hidden;
            background-color: #333;
        }

        .navbar a {
            float: left;
            display: block;
            color: #f2f2f2;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

        .navbar a:hover {
            background-color: #ddd;
            color: black;
        }

        .content {
            margin-top: 20px;
        }

        .button {
            padding: 10px 20px;
            font-size: 16px;
            cursor: pointer;
            border: none;
            border-radius: 5px;
        }

        .login {
            background-color: #007bff;
            color: #fff;
        }

        .signup {
            background-color: #28a745;
            color: #fff;
        }

        .options {
            margin-top: 30px;
        }

        .options a {
            text-decoration: none;
            margin: 10px;
        }

        .options button {
            padding: 10px 20px;
            font-size: 16px;
            cursor: pointer;
            border: none;
            border-radius: 5px;
            background-color: #17a2b8;
            color: #fff;
        }
    </style>
</head>
<body>

    <div class="navbar">
        {% if user.is_authenticated %}
            <a href="{% url 'Grochery:logout' %}" style="float: right;">Log Out</a>
        {% else %}
            <a href="{% url 'Grochery:user_login' %}" style="float: right;">Log In</a>
            <a href="{% url 'Grochery:register' %}" style="float: right;">Sign Up</a>
        {% endif %}
        <a href="{% url 'Grochery:shopping_lists' %}" style="float: right;">Lista alimente</a>
        <a href="{% url 'Grochery:food_list' %}" style="float: right;">Lista cumparaturi</a>
    </div>

    <div class="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

PI/Proiect/templates/Grochery/edit_food.html
<h2>Editare aliment</h2>
<form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Salveaza modificarile</button>
</form>

PI/Proiect/templates/Grochery/food_list.html
<h2>Lista de alimente</h2>
<form method="get" action="{% url 'Grochery:food_list' %}">
    <label for="sort">Sortează după:</label>
    <select name="sort" id="sort">
        <option value="name">Alfabetic</option>
        <option value="-name">Alfabetic invers</option>
        <option value="is_favorite">Favorite</option>
    </select>
    <button type="submit">Sortează</button>
</form>


<ul>
    {% for food in foods %}
        <li>{{ food.name }} - {{ food.price }} {% if food.is_favorite %}(Favorit){% endif %}
            
            <a href="{% url 'Grochery:edit_food' food.id %}"><button>Editează</button></a>
            <form method="post" action="{% url 'Grochery:delete_food' food.id %}" style="display:inline;">
                {% csrf_token %}
                <input type="submit" value="Sterge">
            </form>
        </li>
        
    {% endfor %}
</ul>


<a href="{% url 'Grochery:add_food' %}"><button>Adauga aliment</button></a>
<a href="{% url 'index' %}"><button>Înapoi la Index</button></a>

PI/Proiect/templates/Grochery/index.html
{% extends "Grochery/base.html" %}

{% block title %}
Pagina de Intrare
{% endblock %}

{% block body_block %}
    <div class="content">
        <h1>Bine ați venit!</h1>
        <p>Pentru a avea acces la conținut, vă rugăm să vă autentificați sau să vă înregistrați.</p>
    </div>
{% endblock %}

PI/Proiect/templates/Grochery/inregistrare.html
{% extends "Grochery/base.html" %}

{% block content %}

<div class="jumbotron">
    {% if registered %}
        <h1>Mulțumim pentru înregistrare!</h1>
        <!-- Adaugă un buton pentru a merge la pagina de login -->
        <a class="btn btn-primary" href="{% url 'Grochery:user_login' %}">Login</a>
    {% else %}
        <h1>Înregistrează-te aici</h1>
        <h3>Completează formularul</h3>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            <input type="submit" name="" value="Register">
        </form>

        <!-- Adaugă un buton pentru a merge la pagina de login -->
        <p>Ai deja cont? <a href="{% url 'Grochery:user_login' %}">Login here</a></p>
    {% endif %}
</div>

{% endblock %}

PI/Proiect/templates/Grochery/log_in.html
{% extends "Grochery/base.html" %}

{% block content %}

<div class="jumbotron">
    <h1>Please login</h1>
    <form action="{% url 'Grochery:user_login' %}?next=/Grochery/main_page/" method="POST">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">
    
        <label for="password">Password</label>
        <input type="password" name="password">
    
        <input type="submit" value="Login">
    </form>

    <p>Forgot your password? <a href="{% url 'Grochery:reset_password' %}">Reset it here</a>.</p>
</div>

{% endblock %}

PI/Proiect/templates/Grochery/main.html
{% extends "Grochery/base.html" %}
{% load static %}
{% block body_block %}


    <div class="jumbotron">
        <h1>Bine ai venit, {{ user.username }}!</h1>
        <p>Aici este conținutul special pentru utilizatorii autentificați.</p>
        <a class="btn btn-primary" href="{% url 'Grochery:food_list' %}">Vezi Lista de Alimente</a>
        <a class="btn btn-success" href="{% url 'Grochery:add_food' %}">Adaugă Aliment in Lista de Alimente</a>
        <a class="btn btn-info" href="{% url 'Grochery:shopping_lists' %}">Liste de Cumpărături</a>

    </div>


{% endblock %}

PI/Proiect/templates/Grochery/password_reset_confirm.html
{% extends "Grochery/base.html" %}

{% block content %}

<div class="jumbotron">
    <h1>Resetare parolă</h1>
    <form method="post">
        {% csrf_token %}
        <label for="password">Noua parolă:</label>
        <input type="password" name="password" required>
        
        <label for="confirm_password">Confirmare parolă:</label>
        <input type="password" name="confirm_password" required>
        
        <input type="submit" value="Resetare parolă">
    </form>
</div>

{% endblock %}

PI/Proiect/templates/Grochery/reset_password.html
<!-- În reset_password.html -->
<h1>Resetare parolă</h1>

<form method="post" action="{% url 'Grochery:reset_password' %}">
    {% csrf_token %}
    <label for="email">Introduceți adresa de email:</label>
    <input type="email" name="email" required>
    <button type="submit">Trimite email de resetare</button>
</form>

PI/Proiect/templates/Grochery/shopping_lists.html
<!-- Grochery/shopping_lists.html -->

{% extends "Grochery/base.html" %}
{% block body_block %}

<div class="container">
    <h1>Liste de cumpărături</h1>
    <ul>
        {% for shopping_list in user_lists %}
            <li>
                <a href="{% url 'Grochery:shopping_list_detail' shopping_list.id %}">
                    {{ shopping_list.name }} - {{ shopping_list.meal }}
                </a>
            </li>
        {% endfor %}
    </ul>
    <a class="btn btn-primary" href="{% url 'Grochery:add_shopping_list' %}">Adaugă listă</a>
</div>

{% endblock %}